In [1]:
import pandas as pd

In [2]:
pd

In [5]:
# Store the data in DataFrame
df = pd.read_csv("../data/Walmart.csv")

In [6]:
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [7]:
df.head(10)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106
5,1,12-03-2010,1439541.59,0,57.79,2.667,211.380643,8.106
6,1,19-03-2010,1472515.79,0,54.58,2.720,211.215635,8.106
7,1,26-03-2010,1404429.92,0,51.45,2.732,211.018042,8.106
8,1,02-04-2010,1594968.28,0,62.27,2.719,210.820450,7.808
9,1,09-04-2010,1545418.53,0,65.86,2.770,210.622857,7.808

In [8]:
df.tail()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667

In [9]:
df.shape

(6435, 8)

 6435 number of rows
 8 number of columns

In [10]:
df.columns

Index(['Store', 'Date', 'Weekly_Sales', 'Holiday_Flag', 'Temperature',
       'Fuel_Price', 'CPI', 'Unemployment'],
      dtype='object')

| Column         | What it represents            |
| -------------- | ----------------------------- |
| `Store`        | Store ID                      |
| `Date`         | Week/date of the observation  |
| `Weekly_Sales` | Sales during that week        |
| `Holiday_Flag` | Whether it was a holiday week |
| `Temperature`  | Temperature                   |
| `Fuel_Price`   | Fuel price                    |
| `CPI`          | Consumer Price Index          |
| `Unemployment` | Unemployment rate             |

In [11]:
df.dtypes

Store             int64
Date             object
Weekly_Sales    float64
Holiday_Flag      int64
Temperature     float64
Fuel_Price      float64
CPI             float64
Unemployment    float64
dtype: object

In [ ]:
# Check missing values
df.isnull().sum()

Store           0
Date            0
Weekly_Sales    0
Holiday_Flag    0
Temperature     0
Fuel_Price      0
CPI             0
Unemployment    0
dtype: int64

In [ ]:
# Check duplicate rows
df.duplicated().sum()

0

No duplicated row

In [20]:
# Check how many stores
df["Store"].nunique()

45

In [21]:
# See the actual stores
df["Store"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45], dtype=int64)

### df["Store"].unique()
->Shows the unique values
### df["Store"].nunique()
->Counts the unique values

In [22]:
# Understand our numerical data
df.describe()

,Store,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
count,6435.000000,6.435000e+03,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000
mean,23.000000,1.046965e+06,0.069930,60.663782,3.358607,171.578394,7.999151
std,12.988182,5.643666e+05,0.255049,18.444933,0.459020,39.356712,1.875885
min,1.000000,2.099862e+05,0.000000,-2.060000,2.472000,126.064000,3.879000
25%,12.000000,5.533501e+05,0.000000,47.460000,2.933000,131.735000,6.891000
50%,23.000000,9.607460e+05,0.000000,62.670000,3.445000,182.616521,7.874000
75%,34.000000,1.420159e+06,0.000000,74.940000,3.735000,212.743293,8.622000
max,45.000000,3.818686e+06,1.000000,100.140000,4.468000,227.232807,14.313000

 Count -> Number of observations  
 Mean -> Average  
 Std -> Standard Deviation  
 min -> Smallest value  
 max -> Largest value  
 50% -> Median  
 25% and 75% -> Quartiles

# Cleaning the Date

In [23]:
# Convert the Date column
df["Date"] = pd.to_datetime(df["Date"],dayfirst=True)

In [24]:
df.dtypes

Store                    int64
Date            datetime64[ns]
Weekly_Sales           float64
Holiday_Flag             int64
Temperature            float64
Fuel_Price             float64
CPI                    float64
Unemployment           float64
dtype: object

In [25]:
df["Date"].head()

0   2010-02-05
1   2010-02-12
2   2010-02-19
3   2010-02-26
4   2010-03-05
Name: Date, dtype: datetime64[ns]

In [27]:
df["Date"].min()
# Earliest date in the dataset

Timestamp('2010-02-05 00:00:00')

In [28]:
df["Date"].max()
# Latest date in the dataset

Timestamp('2012-10-26 00:00:00')

.dt means:  
Access datetime-related properties.

In [29]:
df["Date"].dt.year

0       2010
1       2010
2       2010
3       2010
4       2010
        ...
6430    2012
6431    2012
6432    2012
6433    2012
6434    2012
Name: Date, Length: 6435, dtype: int32

In [30]:
df["Date"].dt.month

0        2
1        2
2        2
3        2
4        3
        ..
6430     9
6431    10
6432    10
6433    10
6434    10
Name: Date, Length: 6435, dtype: int32

In [31]:
# Create a Year Column
df["Year"] = df["Date"].dt.year

In [ ]:
df.shape
# New column Year is added
# This is called feature engineering

(6435, 9)

In [ ]:
# Create month Column
df["Month"] = df["Date"].dt.month

In [ ]:
# Number aren't always easy to read in charts

In [37]:
df["Month_Name"] = df["Date"].dt.month_name()

In [38]:
df.shape

(6435, 11)

In [39]:
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month,Month_Name
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106,2010,2,February
1,1,2010-02-12,1641957.44,1,38.51,2.548,211.242170,8.106,2010,2,February
2,1,2010-02-19,1611968.17,0,39.93,2.514,211.289143,8.106,2010,2,February
3,1,2010-02-26,1409727.59,0,46.63,2.561,211.319643,8.106,2010,2,February
4,1,2010-03-05,1554806.68,0,46.50,2.625,211.350143,8.106,2010,3,March

In [40]:
# Create Quarter
df["Quarter"] = df["Date"].dt.quarter

In [41]:
df.shape

(6435, 12)

# Check for suspicious Data

In [43]:
df["Weekly_Sales"].describe()

count    6.435000e+03
mean     1.046965e+06
std      5.643666e+05
min      2.099862e+05
25%      5.533501e+05
50%      9.607460e+05
75%      1.420159e+06
max      3.818686e+06
Name: Weekly_Sales, dtype: float64

In [45]:
# Check weekly_sales is having negative values
df[df["Weekly_Sales"] < 0]

Empty DataFrame
Columns: [Store, Date, Weekly_Sales, Holiday_Flag, Temperature, Fuel_Price, CPI, Unemployment, Year, Month, Month_Name, Quarter]
Index: []

In [ ]:
# Check Temperature
df.Temperature.describe()

count    6435.000000
mean       60.663782
std        18.444933
min        -2.060000
25%        47.460000
50%        62.670000
75%        74.940000
max       100.140000
Name: Temperature, dtype: float64

In [47]:
df[df["Temperature"]<-100]

Empty DataFrame
Columns: [Store, Date, Weekly_Sales, Holiday_Flag, Temperature, Fuel_Price, CPI, Unemployment, Year, Month, Month_Name, Quarter]
Index: []

In [ ]:
# Check Fuel_price
df.Fuel_Price.describe()

count    6435.000000
mean        3.358607
std         0.459020
min         2.472000
25%         2.933000
50%         3.445000
75%         3.735000
max         4.468000
Name: Fuel_Price, dtype: float64

In [50]:
df[df["Fuel_Price"]<=0]

Empty DataFrame
Columns: [Store, Date, Weekly_Sales, Holiday_Flag, Temperature, Fuel_Price, CPI, Unemployment, Year, Month, Month_Name, Quarter]
Index: []

In [51]:
# Check CPI
df.CPI.describe()

count    6435.000000
mean      171.578394
std        39.356712
min       126.064000
25%       131.735000
50%       182.616521
75%       212.743293
max       227.232807
Name: CPI, dtype: float64

In [52]:
df[df["CPI"]<=0]

Empty DataFrame
Columns: [Store, Date, Weekly_Sales, Holiday_Flag, Temperature, Fuel_Price, CPI, Unemployment, Year, Month, Month_Name, Quarter]
Index: []

In [53]:
# Check unemployement
df.Unemployment.describe()

count    6435.000000
mean        7.999151
std         1.875885
min         3.879000
25%         6.891000
50%         7.874000
75%         8.622000
max        14.313000
Name: Unemployment, dtype: float64

In [56]:
df[df["Unemployment"]<0]

Empty DataFrame
Columns: [Store, Date, Weekly_Sales, Holiday_Flag, Temperature, Fuel_Price, CPI, Unemployment, Year, Month, Month_Name, Quarter]
Index: []

In [57]:
# Check Holiday_Flag
df.Holiday_Flag.unique()

array([0, 1], dtype=int64)

In [58]:
df.Holiday_Flag.value_counts()

Holiday_Flag
0    5985
1     450
Name: count, dtype: int64

In [59]:
# Check Store IDs
df.Store.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45], dtype=int64)

An outlier is a value that is unusually far away from most other values.

#### Detect sales outliers using IQR
##### IQR MEAN: Interquartile Range   
##### It is calculated as:  
$$       IQR=Q3-Q1  $$
##### where:
##### * Q1 =25th percentile
##### * Q3 =75th percentile
##### Then we define:

$$ Lower\ Bound = Q1 - 1.5(IQR) $$
$$ Upper Bound=Q3+1.5(IQR) $$

In [60]:
Q1 = df["Weekly_Sales"].quantile(0.25)
Q3 = df["Weekly_Sales"].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 - 1.5 * IQR
print("Q1 : ",Q1)
print("Q3 : ",Q3)
print("IQR : ",IQR)
print("Lower Bound : ",lower_bound)
print("Upper Bound : ",upper_bound)

Q1 :  553350.105
Q3 :  1420158.66
IQR :  866808.5549999999
Lower Bound :  -746862.7275
Upper Bound :  119945.8274999999

In [61]:
outliers = df[
    (df["Weekly_Sales"] < lower_bound) |
    (df["Weekly_Sales"] > upper_bound)
]

In [62]:
outliers.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month,Month_Name,Quarter
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106,2010,2,February,1
1,1,2010-02-12,1641957.44,1,38.51,2.548,211.242170,8.106,2010,2,February,1
2,1,2010-02-19,1611968.17,0,39.93,2.514,211.289143,8.106,2010,2,February,1
3,1,2010-02-26,1409727.59,0,46.63,2.561,211.319643,8.106,2010,2,February,1
4,1,2010-03-05,1554806.68,0,46.50,2.625,211.350143,8.106,2010,3,March,1

In [63]:
outliers.shape

(6435, 12)

Do NOT do this:

df = df.drop(outliers.index)

yet.

Why?

Because we're doing analysis of real Walmart sales.

An unusually high sales value could be completely legitimate.

Instead, we'll investigate the outliers later.

For example:

Store  Date        Weekly Sales
20     2010-12-24  $3,000,000

That might look like an outlier.

But if December 24 is a major holiday period, it may be a perfectly valid observation.

In [64]:
# 10 highest potential sales outliers
outliers.sort_values(
    "Weekly_Sales",
    ascending=False
).head(10)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month,Month_Name,Quarter
1905,14,2010-12-24,3818686.45,0,30.59,3.141,182.544590,8.724,2010,12,December,4
2763,20,2010-12-24,3766687.43,0,25.17,3.141,204.637673,7.484,2010,12,December,4
1333,10,2010-12-24,3749057.69,0,57.06,3.236,126.983581,9.003,2010,12,December,4
527,4,2011-12-23,3676388.98,0,35.92,3.103,129.984548,5.143,2011,12,December,4
1762,13,2010-12-24,3595903.20,0,34.90,2.846,126.983581,7.795,2010,12,December,4
1814,13,2011-12-23,3556766.03,0,24.76,3.186,129.984548,6.392,2011,12,December,4
2815,20,2011-12-23,3555371.03,0,40.19,3.389,212.236040,7.082,2011,12,December,4
475,4,2010-12-24,3526713.39,0,43.21,2.887,126.983581,7.127,2010,12,December,4
1385,10,2011-12-23,3487986.89,0,48.36,3.541,129.984548,7.874,2011,12,December,4
189,2,2010-12-24,3436007.68,0,49.97,2.886,211.064660,8.163,2010,12,December,4

In [65]:
# Check missing dates
df.Date.nunique()

143

In [66]:
df.groupby("Store")["Date"].nunique().describe()

count     45.0
mean     143.0
std        0.0
min      143.0
25%      143.0
50%      143.0
75%      143.0
max      143.0
Name: Date, dtype: float64

# Cleaning the data

In [67]:
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)

In [68]:
df.shape

(6435, 12)

In [69]:
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month,Month_Name,Quarter
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106,2010,2,February,1
1,1,2010-02-12,1641957.44,1,38.51,2.548,211.242170,8.106,2010,2,February,1
2,1,2010-02-19,1611968.17,0,39.93,2.514,211.289143,8.106,2010,2,February,1
3,1,2010-02-26,1409727.59,0,46.63,2.561,211.319643,8.106,2010,2,February,1
4,1,2010-03-05,1554806.68,0,46.50,2.625,211.350143,8.106,2010,3,March,1

In [70]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Month_Name"] = df["Date"].dt.month_name()
df["Quarter"] = df["Date"].dt.quarter

In [71]:
df.shape

(6435, 12)

In [73]:
# Create a week number
df["Week"] = df["Date"].dt.isocalendar().week

In [74]:
df.shape

(6435, 13)

In [75]:
# Check columns
df.columns

Index(['Store', 'Date', 'Weekly_Sales', 'Holiday_Flag', 'Temperature',
       'Fuel_Price', 'CPI', 'Unemployment', 'Year', 'Month', 'Month_Name',
       'Quarter', 'Week'],
      dtype='object')

In [76]:
df.dtypes

Store                    int64
Date            datetime64[ns]
Weekly_Sales           float64
Holiday_Flag             int64
Temperature            float64
Fuel_Price             float64
CPI                    float64
Unemployment           float64
Year                     int32
Month                    int32
Month_Name              object
Quarter                  int32
Week                    UInt32
dtype: object

#### Question?

#### Should we remove outliers
No. ❌

This is important.

We found potential outliers.

But we're not going to automatically remove them.

Why?

Because:

Unusual sales
      ≠
Incorrect sales

For example, Walmart might legitimately have very high sales during a holiday.

So we'll keep them.

Later, during EDA, we'll investigate them.

This is actually something you can mention in an interview:

"I used IQR to identify potential outliers, but I did not automatically remove them because extreme sales values could represent genuine business events such as holiday spikes."

That's a good data-analysis answer.

In [79]:
df.isnull().sum()

Store           0
Date            0
Weekly_Sales    0
Holiday_Flag    0
Temperature     0
Fuel_Price      0
CPI             0
Unemployment    0
Year            0
Month           0
Month_Name      0
Quarter         0
Week            0
dtype: int64

In [80]:
df.duplicated().sum()

0

In [1]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   ---------------------------------------- 0/2 [et-xmlfile]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

# 1. Read the CSV file
df = pd.read_csv("../data/Walmart_cleaned.csv")

# 2. Save as an Excel file
df.to_excel('../data/Walmart_cleaned.xlsx', index=False)